import React from "react";

const TranscriptTab = ({ transcript, aiReview }) => {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
      {/* Transcript Section */}
      <div className="bg-white rounded-lg shadow-md p-8">
        <h2 className="text-3xl font-bold mb-6">Transcript</h2>
        <div className="prose max-w-none text-gray-700">
          {transcript ? (
            <p className="text-lg leading-relaxed">"{transcript}"</p>
          ) : (
            <p className="text-gray-500 italic">
              Transcript will be generated by backend...
            </p>
          )}
        </div>
      </div>

      {/* AI Review Section */}
      <div className="bg-white rounded-lg shadow-md p-8">
        <h2 className="text-3xl font-bold mb-6">AI coach review</h2>
        <div className="prose max-w-none text-gray-700">
          {aiReview ? (
            <p className="text-lg leading-relaxed">"{aiReview}"</p>
          ) : (
            <p className="text-gray-500 italic">
              AI-powered feedback will appear here...
            </p>
          )}
        </div>
      </div>
    </div>
  );
};

export default TranscriptTab;
